---
repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: ''  # Use the sha / tag you want to point at
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #  rev: v2.4.4
  #  hooks:
  #    - id: pylint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: flake8
